const postsData = [
    {  
        id:1,
        title:"Title Blog Post #1",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #1",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        // comment:10,
        like:5,
        authorAvatar:"/images/authors/author_1.jpg",
        image:"/images/posts/post_1.jpg",
    },
    {  
        id:2,
        title:"Title Blog Post #2",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #2",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:1,
        // like:28,
        authorAvatar:"/images/authors/author_2.jpg",
        image:"/images/posts/post_2.jpg",
    },
    {  
        id:3,
        title:"Title Blog Post #3",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #3",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:18,
        like:34,
        authorAvatar:"/images/authors/author_3.jpg",
        image:"/images/posts/post_3.jpg",
    },
    {  
        id:4,
        title:"Title Blog Post #4",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #4",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        // comment:10,
        like:2,
        authorAvatar:"/images/authors/author_4.jpg",
        image:"/images/posts/post_4.jpg",
    },
    {  
        id:5,
        title:"Title Blog Post #5",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #5",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:2,
        like:7,
        authorAvatar:"/images/authors/author_5.jpg",
        image:"/images/posts/post_5.jpg",
    },
    {  
        id:6,
        title:"Title Blog Post #6",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #3",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:3,
        like:22,
        authorAvatar:"/images/authors/author_3.jpg",
        image:"/images/posts/post_6.jpg",
    },
    {  
        id:7,
        title:"Title Blog Post #7",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #7",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:8,
        like:6,
        authorAvatar:"/images/authors/author_7.jpg",
        image:"/images/posts/post_7.jpg",
    },
    {  
        id:8,
        title:"Title Blog Post #8",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #2",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:2,
        like:4,
        authorAvatar:"/images/authors/author_2.jpg",
        image:"/images/posts/post_8.jpg",
    },
    {  
        id:9,
        title:"Title Blog Post #9",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        shortDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam, ea temporibus unde labore, laudantium obcaecati cupiditate tempore inventore iusto distinctio accusamus. Quos laborum adipisci, eum possimus pariatur dolor, odio? Iste!",
        authorName:"Author #6",
        date:"Apri 28, 2016",
        time:"10:15",
        category:"trip",
        tag:"photo",
        comment:19,
        like:45,
        authorAvatar:"/images/authors/author_6.jpg",
        image:"/images/posts/post_9.jpg",
    },
]

export const getPostsMap = (array) => array.reduce((accObj,post)=>({
    ...accObj,
    [post.id]:post,
}),{})


export default postsData
